#!/bin/bash
#Listen for connections to port 2600 and print counter

counter=0

echo "Listening for connections..."
while true;do
    counter=$((counter + 1))
    echo "Hi, 2600 reader! Counter: "$counter"." | nc -l -p 2600 -v
done
