#!/bin/bash

#if temperature is over 65 degress Celcius (in centicelcius value) trigger the FAN 
threshold=60000

while :
do
    temp=$(< /sys/class/thermal/thermal_zone0/temp)

    if [ "$temp" -gt "$threshold" ]; then
        echo 1 > /sys/class/gpio/gpio14/value
    else
        echo 0 > /sys/class/gpio/gpio14/value
    fi  
    sleep 10
done
